version: '3.3'
services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 91981014
       MYSQL_DATABASE: fourseason
       MYSQL_USER: mnkhod
       MYSQL_PASSWORD: 981014

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "9001:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: mnkhod
       WORDPRESS_DB_PASSWORD: 981014
       WORDPRESS_DB_NAME: fourseason
     working_dir: /var/www/html
     volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

volumes:
    db_data: {}
